version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dish_detection_dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.pnpm-store
      - /app/__pycache__
    ports:
      - "3000:3000"   # Frontend (React/Vue/etc)
      - "5000:5000"   # Backend (Flask/FastAPI)
      - "8000:8000"   # Alternative backend port
    environment:
      - NODE_ENV=development
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=1  # For hot reloading in Docker
    working_dir: /app
    command: bash -c "echo 'Development environment ready!' && bash"
    stdin_open: true
    tty: true

  frontend:
    extends: dev
    container_name: dish_detection_frontend
    working_dir: /app/frontend
    command: bash -c "pnpm start 2>/dev/null || pnpm dev 2>/dev/null || pnpm run start 2>/dev/null || pnpm run dev 2>/dev/null || echo 'No frontend start command found. Run pnpm start or pnpm dev manually.'"
    ports:
      - "3000:3000"

  backend:
    extends: dev
    container_name: dish_detection_backend
    working_dir: /app/backend
    command: bash -c "python3 -m uvicorn main:app --host 0.0.0.0 --port 5000 --reload 2>/dev/null || python3 -m flask run --host 0.0.0.0 --port 5000 --debug 2>/dev/null || python3 app.py 2>/dev/null || echo 'No backend start command found. Configure your Python server manually.'"
    ports:
      - "5000:5000"
